urls = '''https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/ballline-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshoe-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/hair-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshort-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/tshirt-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet3.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/fencetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasstile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/cloudtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/startile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlebg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/game_bg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtilesnow-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlechars-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileplaj-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/seatile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/potatiled-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasslinetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileindoor-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/snowtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/ballline-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshoe-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/hair-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshort-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/tshirt-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet3.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/fencetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasstile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/cloudtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/startile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlebg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/game_bg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtilesnow-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlechars-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileplaj-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/seatile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/potatiled-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasslinetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileindoor-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/snowtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/ballline-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshoe-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/hair-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/rightshort-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/tshirt-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet3.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/fencetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasstile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/cloudtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/startile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlebg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/game_bg-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet2.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet1.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-1-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtilesnow-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/buildingtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/titlechars-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileplaj-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/seatile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/potatiled-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/grasslinetile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/groundtileindoor-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile2-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/shared-0-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/indoorbgtile3-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/images/snowtile-sheet0.png
https://files.twoplayergames.org/files/games/other/Basket_Random/media/buttonx.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/start.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/win.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/jump.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-button.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-sound.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bup.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bellsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/goasoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/refsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/file.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/wrong.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/menu.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/press.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/music.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/metal.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/buttonx.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/start.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/win.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/jump.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-button.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-sound.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bup.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bellsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/goasoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/refsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/file.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/wrong.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/menu.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/press.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/music.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/metal.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/buttonx.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/start.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/win.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/jump.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-button.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/intro-sound.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bup.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/bellsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/goasoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/refsoc.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/file.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/wrong.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/menu.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/press.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/music.webm
https://files.twoplayergames.org/files/games/other/Basket_Random/media/metal.webm'''.split("\n")

import requests

for url in urls:
    filepath = url.replace("https://files.twoplayergames.org/files/games/other/Basket_Random/", "./")
    try:
        open(filepath, "r")
        print(f"{filepath} Already Exists")
        continue
    except FileNotFoundError:
        req = requests.get(url)
        text = req.content
        with open(filepath, "bw", encoding=None) as f:
            f.write(text)
            pass